//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.04 at 10:00:29 AM EEST 
//


package org.hkrdi.eden.ggm.vaadin.console.etl.v1;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STAR_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NodeContents">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NodeContent" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="Title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startype",
    "nodeContents"
})
@XmlRootElement(name = "NodeContentCollection")
public class NodeContentCollection {

    @XmlElement(name = "STAR_TYPE", required = true)
    protected String startype;
    @XmlElement(name = "NodeContents", required = true)
    protected NodeContentCollection.NodeContents nodeContents;

    /**
     * Gets the value of the startype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTYPE() {
        return startype;
    }

    /**
     * Sets the value of the startype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTYPE(String value) {
        this.startype = value;
    }

    /**
     * Gets the value of the nodeContents property.
     * 
     * @return
     *     possible object is
     *     {@link NodeContentCollection.NodeContents }
     *     
     */
    public NodeContentCollection.NodeContents getNodeContents() {
        return nodeContents;
    }

    /**
     * Sets the value of the nodeContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeContentCollection.NodeContents }
     *     
     */
    public void setNodeContents(NodeContentCollection.NodeContents value) {
        this.nodeContents = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NodeContent" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="Title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nodeContent"
    })
    public static class NodeContents {

        @XmlElement(name = "NodeContent")
        protected List<NodeContentCollection.NodeContents.NodeContent> nodeContent;

        /**
         * Gets the value of the nodeContent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nodeContent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNodeContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NodeContentCollection.NodeContents.NodeContent }
         * 
         * 
         */
        public List<NodeContentCollection.NodeContents.NodeContent> getNodeContent() {
            if (nodeContent == null) {
                nodeContent = new ArrayList<NodeContentCollection.NodeContents.NodeContent>();
            }
            return this.nodeContent;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="Title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Content" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class NodeContent {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Number")
            protected Integer number;
            @XmlAttribute(name = "Title")
            protected String title;
            @XmlAttribute(name = "Content")
            protected String content;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Integer getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setNumber(Integer value) {
                this.number = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

        }

    }

}
