DROP TABLE IF EXISTS verb_class CASCADE;
DROP TABLE IF EXISTS grid_verb_class CASCADE;
DROP TABLE IF EXISTS grid_projection CASCADE;
DROP TABLE IF EXISTS grid_letter CASCADE;
DROP TABLE IF EXISTS grid_verb CASCADE;
DROP TABLE IF EXISTS grid_conjunction CASCADE;
DROP TABLE IF EXISTS grid CASCADE;