//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.08 at 02:05:52 PM EEST 
//


package org.hkrdi.eden.ggm.vaadin.console.etl.v2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hkrdi.eden.logicalmodel.console.etl.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hkrdi.eden.logicalmodel.console.etl.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SDt }
     * 
     */
    public SDt createSDt() {
        return new SDt();
    }

    /**
     * Create an instance of {@link SDt.T2 }
     * 
     */
    public SDt.T2 createSDtT2() {
        return new SDt.T2();
    }

    /**
     * Create an instance of {@link SDt.T2 .NodeDt }
     * 
     */
    public SDt.T2 .NodeDt createSDtT2NodeDt() {
        return new SDt.T2 .NodeDt();
    }

    /**
     * Create an instance of {@link SDt.T2 .LinkDt }
     * 
     */
    public SDt.T2 .LinkDt createSDtT2LinkDt() {
        return new SDt.T2 .LinkDt();
    }

    /**
     * Create an instance of {@link SDt.T1 }
     * 
     */
    public SDt.T1 createSDtT1() {
        return new SDt.T1();
    }

    /**
     * Create an instance of {@link SDt.T1 .NodeDt }
     * 
     */
    public SDt.T1 .NodeDt createSDtT1NodeDt() {
        return new SDt.T1 .NodeDt();
    }

    /**
     * Create an instance of {@link SDt.T1 .LinkDt }
     * 
     */
    public SDt.T1 .LinkDt createSDtT1LinkDt() {
        return new SDt.T1 .LinkDt();
    }

    /**
     * Create an instance of {@link SDt.T2 .ActivSt }
     * 
     */
    public SDt.T2 .ActivSt createSDtT2ActivSt() {
        return new SDt.T2 .ActivSt();
    }

    /**
     * Create an instance of {@link SDt.T2 .NodeDt.SNodeDt }
     * 
     */
    public SDt.T2 .NodeDt.SNodeDt createSDtT2NodeDtSNodeDt() {
        return new SDt.T2 .NodeDt.SNodeDt();
    }

    /**
     * Create an instance of {@link SDt.T2 .LinkDt.SLinkDt }
     * 
     */
    public SDt.T2 .LinkDt.SLinkDt createSDtT2LinkDtSLinkDt() {
        return new SDt.T2 .LinkDt.SLinkDt();
    }

    /**
     * Create an instance of {@link SDt.T1 .ActivSt }
     * 
     */
    public SDt.T1 .ActivSt createSDtT1ActivSt() {
        return new SDt.T1 .ActivSt();
    }

    /**
     * Create an instance of {@link SDt.T1 .NodeDt.SNodeDt }
     * 
     */
    public SDt.T1 .NodeDt.SNodeDt createSDtT1NodeDtSNodeDt() {
        return new SDt.T1 .NodeDt.SNodeDt();
    }

    /**
     * Create an instance of {@link SDt.T1 .LinkDt.SLinkDt }
     * 
     */
    public SDt.T1 .LinkDt.SLinkDt createSDtT1LinkDtSLinkDt() {
        return new SDt.T1 .LinkDt.SLinkDt();
    }

}
